[General]
DisplayServer=wayland
GreeterEnvironment=QT_QPA_PLATFORM=wayland

[Wayland]
CompositorCommand=weston --shell=fullscreen-shell.so -c /etc/sddm/weston.ini

[Users]
RememberLastUser=true
DefaultUser=@@GAMING_USER@@

[Theme]
Current=starch
